version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/iendorse/Back-API/graphAPI
    overwrite: true  # Ensure new files overwrite existing ones

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu

  # Optional: validate deployment
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 120
      runas: ubuntu
