version: 0.0
os: linux
files:
  - source: /
    destination: /opt/iendorse
    overwrite: yes
    file_exists_behavior: OVERWRITE
permissions:
  - object: /opt/iendorse
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /opt/iendorse
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
  ApplicationReady:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
